from __future__ import annotations

from pathlib import Path
import os
import sys

from PySide6.QtCore import QUrl
from PySide6.QtGui import QGuiApplication, QIcon
from PySide6.QtQml import QQmlApplicationEngine

from techguy_huawei.backend import Backend


def app_root() -> Path:
    # Nuitka onefile resolves __file__ inside its extraction directory, which is
    # where included data files live. In source mode this remains the repo root.
    return Path(__file__).resolve().parent


def main() -> int:
    os.environ.setdefault("QT_QUICK_CONTROLS_STYLE", "Basic")
    app = QGuiApplication(sys.argv)
    app.setOrganizationName("THETECHGUY DIGITAL SOLUTIONS")
    app.setApplicationName("TECHGUY TOOL — HUAWEI")
    root = app_root()
    icon = root / "assets" / "brand" / "techguy_logo.svg"
    if icon.is_file():
        app.setWindowIcon(QIcon(str(icon)))
    engine = QQmlApplicationEngine()
    backend = Backend(root)
    engine.rootContext().setContextProperty("backend", backend)
    try:
        from techguy_huawei import resources_rc  # type: ignore  # generated by pyside6-rcc
        _ = resources_rc
        engine.load(QUrl("qrc:/qml/Main.qml"))
    except ImportError:
        qml = root / "qml" / "Main.qml"
        engine.load(QUrl.fromLocalFile(str(qml)))
    if not engine.rootObjects():
        return 1
    return app.exec()


if __name__ == "__main__":
    raise SystemExit(main())
